storage:
  remote: false
  connection:
    host: 127.0.0.1
    port: 3306
    database: 'ubans'
    username: 'root'
    password: ''

messages:
  no_permission: "&cYou don't have permission to use this command!"
  invalid_duration: "&cEnter a valid duration. ex: 1h25m"
  unbanable: "&cYou can't ban a player who has permission to ban."
  ban:
    usage: "&c/ban <playername> [<duration>] [<reason>]"
    screen:
        - "&cYou have been permanently banned from this server!"
        - ""
        - "&7Reason:"
        - "&6<reason>"
    chat:
      - ""
      - "&e<player> is banned from the server."
      - "&7Reason: &6<reason>"
      - "&7Staff: &6<staff>"
      - ""
  tempban:
    usage: "&c/ban <playername> <duration> [<reason>]"
    screen:
      - "&cYou have been temporarily banned from this server!"
      - ""
      - "&7Reason:"
      - "&6<reason>"
      - ""
      - "&e<duration_left>"
    chat:
      - ""
      - "&e<player> is banned from the server."
      - "&7Reason: &6<reason>"
      - "&7Duration: &6<duration>"
      - "&7Staff: &6<staff>"
      - ""
  unban:
    usage: "&c/unban <playername>"
    success: "&7You have unbanned &e<player>"
    not_banned: "&e<player> &7is not banned."
  history:
    usage: "&c/history <playername>"
    no_history: "&e<player> &chas no records."